// SPDX-License-Identifier: Apache-2.0
// Copyright 2021 The go-steamworks Authors

// Code generated by gen.go. DO NOT EDIT.

package steamworks

import (
	_ "embed"
)

//go:embed steam_api64.dll
var steamAPIDLL []byte

const steamAPIDLLHash = "ca1fa9a7609ab10b7926400559cf073e5888423cc156af72c6027d72a89eea73"
