// SPDX-License-Identifier: Apache-2.0
// Copyright 2021 The go-steamworks Authors

// Code generated by gen.go. DO NOT EDIT.

package steamworks

import (
	_ "embed"
)

//go:embed steam_api.dll
var steamAPIDLL []byte

const steamAPIDLLHash = "ce6f48938493b90ffa175fc93f2b8ee5189e5db81f1274d5b57c9841d6fe4179"
